- name: Create directories
  file:
    path: /home/deploy/var/www/
    state: directory
    owner: deploy
    mode: 0755
  notify: restart nginx

- name: Remove default nginx config
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
