# All roles are installed from Ansible Galaxy
- DavidWittman.redis
- geerlingguy.nodejs
- geerlingguy.passenger
- geerlingguy.postgresql
- kamaln7.swapfile
- manala.git
- manala.zsh
- mashimom.oh-my-zsh
- pgolm.monit
- rvm_io.ruby
