# All roles are installed from Ansible Galaxy
- src: ANXS.postgresql
- src: geerlingguy.nodejs
- src: geerlingguy.passenger
- src: geerlingguy.redis
- src: kamaln7.swapfile
- src: manala.git
- src: manala.zsh
- src: mashimom.oh-my-zsh
- src: pgolm.monit
- src: rvm_io.ruby
