- name: Setup user
  hosts: all
  remote_user: root
  become: yes
  roles:
    - { role: users }
    - { role: manala.git }
    - { role: manala.zsh }
    - { role: mashimom.oh-my-zsh, ohmyzsh_theme: 'aussiegeek' }

- name: Setup user environment
  hosts: rails
  remote_user: deploy
  roles:
    - { role: mashimom.oh-my-zsh, ohmyzsh_theme: 'aussiegeek' }

- name: Install all necessary software
  hosts: rails
  remote_user: deploy
  become: yes
  roles:
    - { role: common }
    - { role: geerlingguy.nodejs }

- name: Add swap file
  hosts: rails
  remote_user: deploy
  become: yes
  roles:
    - role: kamaln7.swapfile
      swapfile_size: 2GB
      swapfile_swappiness: 10
      swapfile_location: /mnt/swapfile

- name: Setup monit
  hosts: rails
  remote_user: root
  roles:
    - { role: pgolm.monit, when: (monit_enabled is defined) and monit_enabled }
    - { role: setup_monit, when: (monit_enabled is defined) and monit_enabled }

- name: Setup nginx and passenger
  hosts: rails
  remote_user: deploy
  become: yes
  vars:
    passenger_root: /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini
    passenger_ruby: /home/deploy/.rvm/gems/ruby-{{ ruby_version }}/wrappers/ruby
    passenger_app_env: production
    passenger_app_root: /home/deploy/var/www/{{ app_name }}/current/public
    passenger_server_name: "{{ app_domain }}"
  roles:
    - { role: geerlingguy.passenger }
    - { role: nginx }

- name: Install redis
  hosts: rails
  remote_user: deploy
  become: yes
  vars:
    - redis_port: 6379
    - redis_bind_interface: 127.0.0.1
  roles:
    - { role: DavidWittman.redis }

- name: Install Ruby
  hosts: rails
  remote_user: deploy
  roles:
    - role: rvm_io.ruby
      rvm1_user: 'deploy'
      become: yes
      rvm1_rubies:
        - 'ruby-{{ ruby_version }}'
    - role: ruby

- name: Install PostgreSQL
  hosts: rails
  remote_user: deploy
  become: yes
  roles:
    # - role: ANXS.postgresql
    #   postgresql_version: 9.5
    #   postgresql_encoding: 'UTF-8'
    #   postgresql_locale: 'en_US.UTF-8'
    #   postgresql_admin_user: 'postgres'
    #   postgresql_default_auth_method: 'trust'
    - role: geerlingguy.postgresql
      postgresql_version: 9.5
      postgresql_locales:
        - 'en_US.UTF-8'
