- name: Add Rails app database and user
  hosts: rails
  remote_user: deploy
  roles:
    - create-rails-database

- name: Turn on https for domains
  hosts: rails
  remote_user: deploy
  become: yes
  roles:
    - issue-ssl-certificates

- name: Automate backups
  hosts: rails
  remote_user: deploy
  roles:
    - role: setup-backuping
      when: aws_backups_enabled
