- name: Setup user environment
  hosts: rails
  remote_user: deploy
  roles:
    - mashimom.oh-my-zsh

- name: Install all necessary software
  hosts: rails
  remote_user: deploy
  become: yes
  roles:
    - common-software
    - manala.fail2ban
    - geerlingguy.nodejs

- name: Add swap file
  hosts: rails
  remote_user: deploy
  become: yes
  roles:
    - role: kamaln7.swapfile
      swapfile_size: 2GB
      swapfile_swappiness: 10
      swapfile_location: /mnt/swapfile_2GB

- name: Setup monit
  hosts: rails
  remote_user: deploy
  become: yes
  roles:
    - { role: pgolm.monit, when: (monit_enabled is defined) and monit_enabled }
    - { role: setup_monit, when: (monit_enabled is defined) and monit_enabled }

- name: Setup nginx
  hosts: rails
  remote_user: deploy
  become: yes
  roles:
    - geerlingguy.nginx
    - nginx

- name: Install redis
  hosts: rails
  remote_user: deploy
  become: yes
  roles:
    - role: DavidWittman.redis
      redis_bind: 127.0.0.1

- name: Install Ruby
  hosts: rails
  remote_user: deploy
  roles:
    - role: rvm_io.ruby
      rvm1_user: deploy
      become: yes
      rvm1_rubies:
        - "ruby-{{ ruby_version }}"
    - role: ruby

- name: Install PostgreSQL
  hosts: rails
  remote_user: deploy
  become: yes
  roles:
    # - role: ANXS.postgresql
    #   postgresql_version: 9.5
    #   postgresql_encoding: 'UTF-8'
    #   postgresql_locale: 'en_US.UTF-8'
    #   postgresql_admin_user: 'postgres'
    #   postgresql_default_auth_method: 'trust'
    - role: geerlingguy.postgresql
      postgresql_version: 9.5
      postgresql_locales:
        - 'en_US.UTF-8'
