- name: Install python for ansible
  hosts: rails
  remote_user: root
  become: yes
  gather_facts: no
  roles:
    - install-python-for-ansible

- name: Setup deploy user
  hosts: rails
  remote_user: root
  become: yes
  roles:
    - create-deploy-user

- name: Install prerequisites
  hosts: rails
  remote_user: root
  become: yes
  roles:
    - manala.git
    - manala.zsh
    - mashimom.oh-my-zsh
