- name: Install python for ansible
  hosts: rails
  remote_user: root
  become: yes
  gather_facts: no
  roles:
    - ansible-python

- name: Setup deploy user
  hosts: rails
  remote_user: root
  become: yes
  roles:
    - deploy-user

- name: Install prerequisites
  hosts: rails
  remote_user: root
  become: yes
  roles:
    - manala.git
    - manala.zsh
    - mashimom.oh-my-zsh
