- name: "Add {{ app_name }} app database"
  postgresql_db:
    name: "{{ db_name }}_{{ env }}"
    encoding: 'UTF-8'
    login_host: 127.0.0.1
    login_user: deploy
    login_password: "{{ postgres_password }}"
