- name: Upload db dump to server
  copy:
    src: "{{ playbook_dir }}/files/{{ db_name }}_{{ env }}.dump"
    dest: /home/deploy/apps/{{ app_name }}-{{ env }}/shared/{{ db_name }}_{{ env }}.dump

- name: Restore database with psql
  shell: >
    pg_restore --clean --format c --verbose
    --no-owner
    --username deploy
    --dbname {{ db_name }}_{{ env }}
    /home/deploy/apps/{{ app_name }}-{{ env }}/shared/{{ db_name }}_{{ env }}.dump
