- name: Upload monit config
  template: src=templates/monitrc.sh dest=/etc/monit/monitrc owner=root
  notify: reload monit

- name: Upload slack webhook script
  template:
    src: templates/slack_notification.sh
    dest: /etc/monit/slack_notification.sh
    owner: deploy

- name: Set rights
  shell: chmod +x /etc/monit/slack_notification.sh
